import { describe, expect, it } from 'vitest';
import {
  findStoredTerminalSession,
  findStoredTerminalSessionByProcessId,
  findUnidentifiedStoredTerminalSessionByFolder,
  isLegacyManagedTerminalName,
  readStoredTerminalSessions,
  type StoredTerminalSession
} from '../src/terminalPersistence';

const first: StoredTerminalSession = {
  id: 'session-1',
  folderId: 'folder-1',
  name: 'Claude API',
  terminalName: 'Terminal 1',
  createdAt: 10
};

const second: StoredTerminalSession = {
  id: 'session-2',
  folderId: 'folder-1',
  name: 'Terminal 2',
  terminalName: 'Terminal 2',
  createdAt: 20,
  processId: 202
};

describe('readStoredTerminalSessions', () => {
  it('keeps valid unique sessions for folders that still exist', () => {
    expect(
      readStoredTerminalSessions(
        [first, { ...first, name: 'duplicate' }, second, { ...second, id: 'gone', folderId: 'folder-2' }],
        new Set(['folder-1'])
      )
    ).toEqual([first, second]);
  });

  it('drops malformed storage values', () => {
    expect(
      readStoredTerminalSessions(
        [
          null,
          { ...first, terminalName: '' },
          { ...first, createdAt: Number.NaN },
          { ...first, processId: -1 }
        ],
        new Set(['folder-1'])
      )
    ).toEqual([]);
  });
});

describe('findStoredTerminalSessionByProcessId', () => {
  it('matches a restored native terminal when VS Code strips its creation options', () => {
    expect(
      findStoredTerminalSessionByProcessId(
        [first, second],
        new Set(),
        second.processId!,
        second.folderId
      )
    ).toEqual(second);
  });

  it('does not reuse a session or cross folder boundaries', () => {
    expect(
      findStoredTerminalSessionByProcessId(
        [second],
        new Set([second.id]),
        second.processId!
      )
    ).toBeUndefined();
    expect(
      findStoredTerminalSessionByProcessId(
        [second],
        new Set(),
        second.processId!,
        'folder-2'
      )
    ).toBeUndefined();
  });
});

describe('findUnidentifiedStoredTerminalSessionByFolder', () => {
  it('supports metadata saved before process IDs were introduced', () => {
    expect(
      findUnidentifiedStoredTerminalSessionByFolder(
        [first, second],
        new Set(),
        first.folderId
      )
    ).toEqual(first);
  });

  it('leaves process-identified sessions for exact matching', () => {
    expect(
      findUnidentifiedStoredTerminalSessionByFolder(
        [second],
        new Set(),
        second.folderId
      )
    ).toBeUndefined();
  });
});

describe('findStoredTerminalSession', () => {
  it('prefers the stable marker even when the native name changed', () => {
    expect(
      findStoredTerminalSession([first, second], new Set(), {
        markerSessionId: second.id,
        markerFolderId: second.folderId,
        folderId: first.folderId,
        terminalName: 'changed title'
      })
    ).toEqual(second);
  });

  it('falls back to folder and native name for terminals from older releases', () => {
    expect(
      findStoredTerminalSession([first, second], new Set([first.id]), {
        folderId: second.folderId,
        terminalName: second.terminalName
      })
    ).toEqual(second);
  });

  it('does not fall back when an unknown marker is present', () => {
    expect(
      findStoredTerminalSession([first], new Set(), {
        markerSessionId: 'someone-else',
        folderId: first.folderId,
        terminalName: first.terminalName
      })
    ).toBeUndefined();
  });
});

describe('isLegacyManagedTerminalName', () => {
  it('recognizes only the names generated by TerminalFolder', () => {
    expect(isLegacyManagedTerminalName('Terminal 1')).toBe(true);
    expect(isLegacyManagedTerminalName('Terminal 01')).toBe(false);
    expect(isLegacyManagedTerminalName('Claude')).toBe(false);
  });
});
